{{- if .Values.tester.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.tester.serviceAccount.name }}
  namespace: {{ include "admpool.saNamespace" . }}
  labels:
    {{- include "admpool.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
