# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Documentation and reproduction
  Annex A rows for Documentation and reproduction, worded exactly as in the Annex.

  @ZT-16 @BDD-ZT-016 @pending
  Scenario: Cloud Environments
    Given the accepted release baseline
    When cloud environments documentation is generated from the repository
    Then the documented setup/usage can be reproduced step by step and the documentation is buildable from GitHub.

  @ZT-17 @BDD-ZT-017 @pending
  Scenario: Demonstrator Usage
    Given the accepted release baseline
    When demonstrator usage documentation is generated from the repository
    Then the documented setup/usage can be reproduced step by step and the documentation is buildable from GitHub.

  @ZT-42 @BDD-ZT-042 @ZT-79 @BDD-ZT-079 @pending
  Scenario: UX Concept / Visualization Concept
    Given the initial demonstrator flow
    When the wireframe/visualization concept is reviewed with FACIS
    Then the concept is documented in GitHub and the client approval record is captured before UI implementation proceeds.
