# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Final acceptance
  Annex A rows for Final acceptance, worded exactly as in the Annex.

  @M7-01 @BDD-M7-001 @pending
  Scenario: Final Validation and Demonstration
    Given the release accepted at G6 and the agreed target environment
    When the final validation session is executed with FACIS
    Then the complete approved user journey, the positive path and the refusal paths are demonstrated end to end AND every demonstrated state is traceable to the per-gate evidence bundle AND no open Critical/High release blocker is present.

  @M7-02 @BDD-M7-002 @pending
  Scenario: Joint Final Report
    Given the completed per-gate evidence bundles and the accepted release
    When the joint final report is prepared and reviewed with FACIS
    Then the report is complete and every one of its five required references resolves to the referenced artefact AND the client records its acceptance of the report.
