# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: ORCE automation QA
  Annex A rows for ORCE automation QA, worded exactly as in the Annex.

  @TDR-BDD-06 @BDD-TDR-006 @cluster
  Scenario: Structured logging and ORCE errors
    Given a controlled error condition
    When it is triggered
    Then the corresponding log is structured JSON and the machine-readable error is available through the ORCE context.
