# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Visualization and journey
  Annex A rows for Visualization and journey, worded exactly as in the Annex.

  @ZT-05 @BDD-ZT-005 @pending
  Scenario: Communication Visualization
    Given the client-approved visualization concept and a running FACIS.ZTD demonstrator
    When the communication-visualization scenario is exercised through the ORCE-orchestrated user journey
    Then the demonstrator visibly presents connection and trust state, the decisions taken and the resulting communication outcomes to an external audience AND a blocked communication is presented with its refusal reason.

  @ZT-08 @BDD-ZT-008 @pending
  Scenario: Visualization
    Given the client-approved visualization concept and a running demonstrator
    When an external observer follows the demonstrator flow in the UI
    Then the key Zero Trust functionality and the complete flow are presented comprehensibly in the approved form AND a step that produces no visible outcome is recorded as a defect.

  @ZT-09 @BDD-ZT-009 @pending
  Scenario: User Journey
    Given the client-aligned user-journey scenario configured in ORCE
    When the journey is run from participant registration through to the protected-resource response
    Then ORCE orchestrates each step in sequence and the complete end-to-end Zero Trust flow is demonstrated AND a failing step halts the journey with its reason shown.

  @ZT-43 @BDD-ZT-043 @pending
  Scenario: ORCE Usage
    Given the demonstrator deployed with ORCE as the orchestration runtime
    When the visualization user journey is executed
    Then every step of the journey is driven by an ORCE flow that is identifiable in the ORCE runtime AND no journey step bypasses ORCE.

  @ZT-44 @BDD-ZT-044 @pending
  Scenario: Value Visualization
    Given the client-aligned value-visualization concept and a running demonstrator
    When the user journey produces trust and communication outcomes
    Then the demonstrator presents the TEE measurements, credentials, TRAIN zones, communication decisions and messages defined in the concept AND a value that cannot be obtained is shown as unavailable rather than omitted.

  @ZT-45 @BDD-ZT-045 @pending
  Scenario: Demonstrator Configuration
    Given the documented demonstrator configuration interface
    When an operator changes the TRAIN zone and policy configuration through it
    Then the change is applied and reflected in the running demonstrator AND an invalid configuration is rejected with a machine-readable error.

  @ZT-46 @BDD-ZT-046 @ZT-81 @BDD-ZT-081 @pending
  Scenario: User Journey Scenario
    Given the client-approved user journey
    When it is executed in ORCE
    Then the journey is shown step by step, including credential issuance/presentation, trust decisions, protected-resource access and visual outcomes.

  @ZT-78 @BDD-ZT-078 @pending
  Scenario: Visualization UI
    Given the client-approved visualization concept and a running FACIS.ZTD demonstrator
    When the visualization UI is exercised through the ORCE-orchestrated user journey
    Then the UI presents the core Zero Trust values, namely connection status, mocked TEE measurement values, and sent and blocked messages AND a blocked message is shown with its reason.

  @ZT-80 @BDD-ZT-080 @pending
  Scenario: Zero Trust Configuration
    Given the approved demonstrator configuration interface
    When an authorized operator changes supported settings such as protected resources, participant backends, mock replacement, attestation procedure or DNS/scenario configuration
    Then the selected configuration is applied and reflected by the demonstrator AND invalid configuration is rejected with a machine-readable error.
