#!/usr/bin/env bash
# The upstream state behind the mesh-mode decision (docs/adr/0009), recorded from the sources and
# never written by hand. It is also the reopen check that record names: it exits 0 while every
# premise of the decision holds, and non-zero, naming the premise, when one has moved.
#
# Fetched and recorded, into docs/evidences/mesh-mode-upstream-state/:
#   - the latest Istio release;
#   - the migration guide's "What is not supported" entry for SPIRE, with the fetched excerpt;
#   - the state of istio/istio#42339 (SPIRE under ambient) and of istio/ztunnel#1676 (Delegated
#     Identity API), #1936 (SPIFFE Broker API client) and #2067 (per-workload cache groundwork);
#   - the latest SPIRE release and whether doc/spire_agent.md at that release still places the
#     Broker API under the `experimental` configuration block.
#
# Exit status:
#   0  every premise holds: the record and environment.json are written
#   1  a premise moved (the statement is gone, a client pull request merged, the Broker API left
#      the experimental block); the record names it
#   2  a source was unreachable; the record says so and claims nothing about that source. A source
#      counts as unreachable when it cannot be fetched, when it answers with an HTTP error status
#      (a 404 or 500 error page is never read as the document), and when it answers with a document
#      that lacks the expected shape (the migration guide's title MIGRATE_TITLE, the SPIRE agent
#      document's first line SPIRE_DOC_HEADING, a release's version-shaped tag); the record names
#      the shape that was expected
#   3  refused: CI must never write this evidence (set ALLOW_CI=1 to override on purpose)
#
# Needs curl and jq; uses gh for the GitHub API when it is installed and logged in (no rate
# limit), curl otherwise. python3 turns the migration guide's HTML into text.
#   OUT_DIR            where the record goes (default: docs/evidences/mesh-mode-upstream-state in the repo)
#   ISTIO_MIGRATE_URL  the migration guide (default: the latest guide on istio.io); a file:// URL
#   GITHUB_API         the GitHub API base (default: https://api.github.com); and
#   SPIRE_DOC_BASE     the raw-content base for the SPIRE document (default: raw.githubusercontent.com)
#                      exist so the failure paths can be exercised against local copies
# The failure paths are tested by scripts/mesh-mode/check-upstream-state-test.sh against a local
# server (CI runs it with the record in a temporary directory, never in docs/evidences/).
set -uo pipefail

if [ -n "${CI:-}" ] && [ -z "${ALLOW_CI:-}" ]; then
  echo "refusing to run under CI: the upstream-state record is regenerated by an operator and committed, never written by a pipeline" >&2
  exit 3
fi
for tool in curl jq python3 git; do
  command -v "$tool" >/dev/null || { echo "missing tool: $tool" >&2; exit 2; }
done

REPO=$(git -C "$(dirname "$0")" rev-parse --show-toplevel) || exit 2
OUT_DIR=${OUT_DIR:-$REPO/docs/evidences/mesh-mode-upstream-state}
if ! mkdir -p "$OUT_DIR" || ! OUT_DIR=$(cd "$OUT_DIR" && pwd -P); then echo "cannot create $OUT_DIR" >&2; exit 2; fi
RECORD=$OUT_DIR/upstream-state.md
ENVIRONMENT=$OUT_DIR/environment.json
NOW=$(date -u +%Y-%m-%dT%H:%M:%SZ)

ISTIO_MIGRATE_URL=${ISTIO_MIGRATE_URL:-https://istio.io/latest/docs/ambient/migrate/}
GITHUB_API=${GITHUB_API:-https://api.github.com}
SPIRE_DOC_BASE=${SPIRE_DOC_BASE:-https://raw.githubusercontent.com/spiffe/spire}
ISTIO_STATEMENT="SPIRE as the certificate provider"
ISTIO_STATEMENT_DETAIL="Ambient mode does not support SPIRE integration"
# The shape of each fetched document, checked before it is read: an answer without it is not the
# document asked for (an error page, a redirect to another page) and counts as unreachable.
MIGRATE_TITLE="Migrate from Sidecar to Ambient"               # the migration guide's page title
SPIRE_DOC_HEADING="# SPIRE Agent Configuration Reference"     # the agent document's first line
ISTIO_ISSUE=42339
ZTUNNEL_PRS=(1676 1936 2067)
declare -A ZTUNNEL_PR_ROLE=(
  [1676]="Delegated Identity API client (ztunnel as a SPIRE delegate)"
  [1936]="SPIFFE Broker API client"
  [2067]="per-workload keys in the certificate cache (groundwork only)"
)
SPIRE_AGENT_DOC_PATH=doc/spire_agent.md

# ---------------------------------------------------------------------------------------------
# Fetching. gh when it is usable, so the GitHub API is not rate-limited; curl otherwise.
# ---------------------------------------------------------------------------------------------
FETCHER=curl
if command -v gh >/dev/null && gh auth status -h github.com >/dev/null 2>&1; then FETCHER=gh; fi

api_get() { # api_get <github api path, e.g. repos/istio/istio/releases/latest>  -> JSON on stdout
  if [ "$FETCHER" = gh ] && [ "$GITHUB_API" = https://api.github.com ]; then
    gh api "$1" 2>/dev/null
  else
    curl -sSL --fail -m 30 -H 'Accept: application/vnd.github+json' "$GITHUB_API/$1"
  fi
}
# --fail: an HTTP error status is a failed fetch, never a body to read (gh api already fails so)
raw_get() { curl -sSL --fail -m 30 "$1"; }

unreachable=()  # sources that could not be fetched
moved=()        # premises that no longer hold
notes=()        # observations that do not change the verdict but belong in the record
note() { printf '%s\n' "$*" >&2; }
# Every fetched string is written through this: the record is a published docs page and
# Python-Markdown passes raw HTML through, so markup, table pipes and line breaks in upstream
# text (titles, labels, excerpts, quotes) must arrive as text, never as structure.
esc() { printf '%s' "$1" | tr '\r\n' '  ' | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/|/\&#124;/g'; }
# A release tag is spliced into a URL path: accept only a version-shaped one.
is_tag() { [[ $1 =~ ^v?[0-9]+(\.[0-9]+)*$ ]]; }

# ---------------------------------------------------------------------------------------------
# Condition 1 — Istio
# ---------------------------------------------------------------------------------------------
istio_release_json=$(api_get repos/istio/istio/releases/latest) && [ -n "$istio_release_json" ] \
  || { unreachable+=("istio/istio latest release (GitHub API)"); istio_release_json=; }
istio_tag=$(jq -r '.tag_name // empty' <<<"$istio_release_json")
istio_published=$(jq -r '.published_at // empty' <<<"$istio_release_json")
if [ -z "$istio_tag" ]; then
  [ -n "$istio_release_json" ] && unreachable+=("istio/istio latest release: no tag in the response")
elif ! is_tag "$istio_tag"; then
  unreachable+=("istio/istio latest release: tag $istio_tag is not version-shaped; not recorded"); istio_tag=; istio_published=
fi

migrate_html=$(raw_get "$ISTIO_MIGRATE_URL") && [ -n "$migrate_html" ] \
  || { unreachable+=("Istio migration guide $ISTIO_MIGRATE_URL"); migrate_html=; }
if [ -n "$migrate_html" ] && ! grep -qF "$MIGRATE_TITLE" <<<"$migrate_html"; then
  unreachable+=("Istio migration guide $ISTIO_MIGRATE_URL: the answer is not the guide (expected the title \"$MIGRATE_TITLE\"); not read")
  migrate_html=
fi
migrate_text=
migrate_version=
statement_found=no
statement_excerpt=
if [ -n "$migrate_html" ]; then
  migrate_text=$(printf '%s' "$migrate_html" | python3 -c '
import html, re, sys
s = sys.stdin.read()
s = re.sub(r"<script.*?</script>|<style.*?</style>", " ", s, flags=re.S)
s = re.sub(r"<[^>]+>", " ", s)
# entities are decoded after the tags are gone, and decoded a second time so that an
# entity-encoded tag (&lt;img ...&gt;, or doubly encoded) comes out as text and is stripped too
s = html.unescape(html.unescape(s))
s = re.sub(r"<[^>]+>", " ", s)
print(re.sub(r"\s+", " ", s).strip())
')
  migrate_version=$(grep -oE 'Version Istio [0-9]+\.[0-9]+(\.[0-9]+)?' <<<"$migrate_text" | head -1 | sed 's/Version Istio //')
  if grep -qF "$ISTIO_STATEMENT" <<<"$migrate_text"; then
    statement_found=yes
    # the entry with its neighbours, so the heading it sits under is visible
    statement_excerpt=$(python3 -c '
import sys
text = sys.stdin.read()
needle = sys.argv[1]
i = text.find(needle)
start = max(0, i - 220)
end = min(len(text), i + 160)
# cut on word boundaries: forward to the next space after start, back to the last space before end
if start > 0:
    j = text.find(" ", start)
    start = j + 1 if 0 <= j < i else start
if end < len(text):
    j = text.rfind(" ", i, end)
    end = j if j > i else end
print(("…" if start > 0 else "") + text[start:end].strip() + ("…" if end < len(text) else ""))
' "$ISTIO_STATEMENT" <<<"$migrate_text")
    grep -qF "$ISTIO_STATEMENT_DETAIL" <<<"$migrate_text" || notes+=("Istio: the entry is present but its explanatory sentence (\"$ISTIO_STATEMENT_DETAIL\") is not; the wording changed, see the excerpt")
    grep -qF "What is not supported" <<<"$migrate_text" || notes+=("Istio: the heading \"What is not supported\" was not found on the page; the entry is recorded from the page text and its placement is not confirmed")
  else
    moved+=("Istio: the migration guide no longer contains \"$ISTIO_STATEMENT\" (condition 1 may have moved: check whether ambient mode now documents SPIRE as supported)")
  fi
fi

issue_json=$(api_get "repos/istio/istio/issues/$ISTIO_ISSUE") && [ -n "$issue_json" ] \
  || { unreachable+=("istio/istio#$ISTIO_ISSUE (GitHub API)"); issue_json=; }
issue_state=$(jq -r '.state // empty' <<<"$issue_json")
issue_title=$(jq -r '.title // empty' <<<"$issue_json")
issue_updated=$(jq -r '.updated_at // empty' <<<"$issue_json")
issue_closed=$(jq -r '.closed_at // empty' <<<"$issue_json")
issue_reason=$(jq -r '.state_reason // empty' <<<"$issue_json")
[ -z "$issue_json" ] || [ -n "$issue_state" ] || unreachable+=("istio/istio#$ISTIO_ISSUE: no state in the response")

declare -A pr_state pr_merged pr_draft pr_title pr_labels pr_updated
for n in "${ZTUNNEL_PRS[@]}"; do
  pr_json=$(api_get "repos/istio/ztunnel/pulls/$n") && [ -n "$pr_json" ] \
    || { unreachable+=("istio/ztunnel#$n (GitHub API)"); pr_json=; }
  pr_state[$n]=$(jq -r '.state // empty' <<<"$pr_json")
  pr_merged[$n]=$(jq -r '.merged_at // empty' <<<"$pr_json")
  pr_draft[$n]=$(jq -r '.draft // empty' <<<"$pr_json")
  pr_title[$n]=$(jq -r '.title // empty' <<<"$pr_json")
  pr_labels[$n]=$(jq -r '[.labels[]?.name] | join(", ")' <<<"$pr_json")
  pr_updated[$n]=$(jq -r '.updated_at // empty' <<<"$pr_json")
  [ -z "$pr_json" ] || [ -n "${pr_state[$n]}" ] || unreachable+=("istio/ztunnel#$n: no state in the response")
done
# The client pull requests are the ones whose merge moves the premise; #2067 is groundwork and is
# recorded, not judged.
for n in 1676 1936; do
  if [ -n "${pr_merged[$n]}" ]; then
    moved+=("Istio: istio/ztunnel#$n (${ZTUNNEL_PR_ROLE[$n]}) merged on ${pr_merged[$n]} (condition 1 is moving: check the next release notes for SPIRE support in ambient mode)")
  fi
done

# ---------------------------------------------------------------------------------------------
# Condition 2 — SPIRE
# ---------------------------------------------------------------------------------------------
spire_release_json=$(api_get repos/spiffe/spire/releases/latest) && [ -n "$spire_release_json" ] \
  || { unreachable+=("spiffe/spire latest release (GitHub API)"); spire_release_json=; }
spire_tag=$(jq -r '.tag_name // empty' <<<"$spire_release_json")
spire_published=$(jq -r '.published_at // empty' <<<"$spire_release_json")
if [ -z "$spire_tag" ]; then
  [ -n "$spire_release_json" ] && unreachable+=("spiffe/spire latest release: no tag in the response")
elif ! is_tag "$spire_tag"; then
  unreachable+=("spiffe/spire latest release: tag $spire_tag is not version-shaped; the agent document was not fetched"); spire_tag=; spire_published=
fi

broker_documented=unknown     # yes | no | unknown
broker_experimental=unknown   # yes | no | unknown
broker_status_line=
spire_doc_url=
if [ -n "$spire_tag" ]; then
  spire_doc_url="$SPIRE_DOC_BASE/$spire_tag/$SPIRE_AGENT_DOC_PATH"
  spire_doc=$(raw_get "$spire_doc_url") && [ -n "$spire_doc" ] \
    || { unreachable+=("SPIRE agent documentation at $spire_tag ($spire_doc_url)"); spire_doc=; }
  if [ -n "$spire_doc" ]; then
    spire_doc_first=$(awk 'NF { sub(/\r$/, ""); sub(/[[:space:]]+$/, ""); print; exit }' <<<"$spire_doc")
    if [ "$spire_doc_first" != "$SPIRE_DOC_HEADING" ]; then
      unreachable+=("SPIRE agent documentation at $spire_tag ($spire_doc_url): the answer is not the document (expected the first line \"$SPIRE_DOC_HEADING\"); not read")
      spire_doc=
    fi
  fi
  if [ -n "$spire_doc" ]; then
    # shellcheck disable=SC2016 # the backticks are Markdown, matched literally
    if grep -qiE '^## .*SPIFFE Broker API|^\| `broker`' <<<"$spire_doc"; then
      broker_documented=yes
      # the table whose header is `| experimental` (any case), up to its first blank line
      experimental_block=$(awk 'tolower($0) ~ /^\| *experimental/{p=1} p&&/^[[:space:]]*$/{exit} p' <<<"$spire_doc")
      [ -n "$experimental_block" ] || notes+=("SPIRE: no table headed \"experimental\" was found in $SPIRE_AGENT_DOC_PATH at $spire_tag; the placement is judged against an empty table")
      # shellcheck disable=SC2016 # as above
      if grep -qE '^\| `broker`' <<<"$experimental_block"; then broker_experimental=yes; else broker_experimental=no; fi
      # the status note is a block quote of several lines; join it
      broker_status_line=$(awk '/^> \*\*Status:\*\*/{p=1} p&&!/^>/{exit} p{sub(/^> ?/,""); printf "%s ", $0}' <<<"$spire_doc" | sed 's/ *$//')
      # cross-check the table placement against the Broker API section's own status note
      if [ -n "$broker_status_line" ]; then
        status_says_experimental=no; grep -qi 'experimental' <<<"$broker_status_line" && status_says_experimental=yes
        if [ "$broker_experimental" = no ] && [ "$status_says_experimental" = yes ]; then
          notes+=("SPIRE: the broker key is not in the experimental table but the Broker API section's status note still says experimental; the table decides, the operator judges")
        elif [ "$broker_experimental" = yes ] && [ "$status_says_experimental" = no ]; then
          notes+=("SPIRE: the broker key is in the experimental table but the Broker API section's status note no longer says experimental; the table decides, the operator judges")
        fi
      fi
      if [ "$broker_experimental" = no ]; then
        moved+=("SPIRE: $SPIRE_AGENT_DOC_PATH at $spire_tag documents the Broker API outside the experimental block (condition 2 may have moved: check the release notes for the Broker API's stability)")
      fi
    else
      broker_documented=no
      broker_experimental=no
    fi
  fi
fi

# ---------------------------------------------------------------------------------------------
# Environment: the commit the record was made on, whether the tree was clean, the host, the tools.
# The dirty flag ignores the evidence folder itself, which this run rewrites.
# ---------------------------------------------------------------------------------------------
commit=$(git -C "$REPO" rev-parse HEAD 2>/dev/null)
dirty=false
exclude=()
case $OUT_DIR in "$REPO"/*) exclude=(":!${OUT_DIR#"$REPO"/}");; esac   # outside the repo there is nothing to exclude
if porcelain=$(git -C "$REPO" status --porcelain -- . "${exclude[@]}"); then
  [ -z "$porcelain" ] || dirty=true
else
  dirty=true; notes+=("the working tree could not be inspected (git status failed); recorded as dirty")
fi
gh_version=$(command -v gh >/dev/null && gh --version 2>/dev/null | head -1 | sed 's/^gh version //')
curl_version=$(curl --version | head -1 | awk '{print $2}')
jq_version=$(jq --version 2>/dev/null | sed 's/^jq-//')
python_version=$(python3 --version 2>/dev/null | awk '{print $2}')
# shellcheck disable=SC1091 # read at run time, not followed
host_os=$( (. /etc/os-release 2>/dev/null && printf '%s' "${PRETTY_NAME:-}") || true)
[ -n "$host_os" ] || host_os=$(uname -s)

# ---------------------------------------------------------------------------------------------
# Verdict
# ---------------------------------------------------------------------------------------------
status=0
if [ ${#unreachable[@]} -gt 0 ]; then status=2; fi
if [ ${#moved[@]} -gt 0 ]; then status=1; fi   # a moved premise outranks a missing source: it is the finding
case $status in
  0) verdict="The premises of ADR-0009 hold: SPIRE as the certificate provider is still documented as unsupported in ambient mode, no ztunnel client for the SPIRE agent has merged, and the SPIRE Broker API is still experimental. The decision stays closed." ;;
  1) verdict="**A premise has moved.** The decision is to be re-examined against the double condition of ADR-0009; the moved premise is named below. One condition alone does not reopen it." ;;
  2) verdict="**No verdict.** A source could not be fetched; this run says nothing about what it could not read. Re-run when the source is reachable." ;;
esac

{
  echo "# Mesh mode: upstream state ($NOW)"
  echo
  echo "Generated by \`scripts/mesh-mode/check-upstream-state.sh\` on commit \`${commit:0:12}\`$( [ "$dirty" = true ] && printf ' (dirty tree)' ). Never edited by hand."
  echo "This is the documentary evidence behind [ADR-0009](../../adr/0009-service-mesh-mode-istio-sidecar-with-cilium.md) and the check of its reopen trigger: both conditions below must be met, in released versions, for the decision to be reopened."
  echo
  echo "## Verdict"
  echo
  echo "$verdict"
  if [ ${#moved[@]} -gt 0 ]; then
    echo
    for m in "${moved[@]}"; do echo "- MOVED: $(esc "$m")"; done
  fi
  if [ ${#unreachable[@]} -gt 0 ]; then
    echo
    for u in "${unreachable[@]}"; do echo "- UNREACHABLE: $(esc "$u")"; done
  fi
  if [ ${#notes[@]} -gt 0 ]; then
    echo
    for n in "${notes[@]}"; do echo "- NOTE: $(esc "$n")"; done
  fi
  echo
  echo "## Condition 1: a community Istio release whose ztunnel takes workload certificates from the SPIRE agent, documented as supported in ambient mode"
  echo
  echo "- Latest Istio release: ${istio_tag:-unreachable}${istio_published:+ ($(esc "$istio_published"))}"
  echo "- Migration guide: <$ISTIO_MIGRATE_URL>${migrate_version:+ (page version Istio $migrate_version)}"
  if [ -z "$migrate_html" ]; then
    echo "- Entry \"$ISTIO_STATEMENT\" under *What is not supported*: **unreachable, not judged**"
  elif [ "$statement_found" = yes ]; then
    echo "- Entry \"$ISTIO_STATEMENT\" under *What is not supported*: **present**"
    echo
    echo "  > $(esc "$statement_excerpt")"
  else
    echo "- Entry \"$ISTIO_STATEMENT\" under *What is not supported*: **not found on the page**"
  fi
  echo "- Tracking issue istio/istio#$ISTIO_ISSUE${issue_title:+ \"$(esc "$issue_title")\"}: $(esc "${issue_state:-unreachable}")${issue_reason:+ ($(esc "$issue_reason"))}${issue_updated:+, last updated $(esc "$issue_updated")}${issue_closed:+, closed $(esc "$issue_closed")}"
  echo
  echo "| ztunnel pull request | Role | State | Merged | Labels | Last updated |"
  echo "|---|---|---|---|---|---|"
  for n in "${ZTUNNEL_PRS[@]}"; do
    st=$(esc "${pr_state[$n]:-unreachable}")
    [ "${pr_draft[$n]}" = true ] && st="$st (draft)"
    echo "| [#$n](https://github.com/istio/ztunnel/pull/$n)${pr_title[$n]:+ \"$(esc "${pr_title[$n]}")\"} | ${ZTUNNEL_PR_ROLE[$n]} | $st | $(esc "${pr_merged[$n]:-no}") | $(esc "${pr_labels[$n]:-}") | $(esc "${pr_updated[$n]:-}") |"
  done
  echo
  echo "The premise moves when the entry disappears from the guide or when #1676 or #1936 merges; #2067 is groundwork and is recorded for context."
  echo
  echo "## Condition 2: a SPIRE release in which the Broker API is a stable agent feature, outside the \`experimental\` block"
  echo
  echo "- Latest SPIRE release: ${spire_tag:-unreachable}${spire_published:+ ($(esc "$spire_published"))}"
  if [ -n "$spire_doc_url" ] && [ "$broker_documented" != unknown ]; then echo "- Agent documentation read: <$spire_doc_url>"
  elif [ -n "$spire_doc_url" ]; then echo "- Agent documentation asked for, not read: <$spire_doc_url>"; fi
  case "$broker_documented/$broker_experimental" in
    yes/yes) echo "- Broker API in \`$SPIRE_AGENT_DOC_PATH\` at ${spire_tag}: documented, **under the \`experimental\` block**${broker_status_line:+ (\"$(esc "$broker_status_line")\")}" ;;
    yes/no)  echo "- Broker API in \`$SPIRE_AGENT_DOC_PATH\` at ${spire_tag}: documented, **outside the \`experimental\` block**${broker_status_line:+ (\"$(esc "$broker_status_line")\")}" ;;
    no/*)    echo "- Broker API in \`$SPIRE_AGENT_DOC_PATH\` at ${spire_tag}: **not documented in this release** (the premise holds: no stable Broker API)" ;;
    *)       echo "- Broker API in \`$SPIRE_AGENT_DOC_PATH\`: **unreachable, not judged**" ;;
  esac
  echo
  echo "The premise moves when the \`broker\` key leaves the \`experimental\` table of the agent configuration at the latest release."
  echo
  echo "## How it was fetched"
  echo
  echo "GitHub API through \`$FETCHER\`; the migration guide and the SPIRE document through \`curl\`. Host, tool versions and commit are in \`environment.json\` next to this file."
} > "$RECORD"

jq -n \
  --arg generatedAt "$NOW" --arg commit "$commit" --argjson dirty "$dirty" \
  --arg fetcher "$FETCHER" --arg gh "${gh_version:-}" --arg curl "$curl_version" --arg jq "$jq_version" --arg python3 "$python_version" \
  --arg os "$host_os" --arg kernel "$(uname -r)" --arg arch "$(uname -m)" \
  --argjson status "$status" \
  --arg istioTag "$istio_tag" --arg spireTag "$spire_tag" \
  '{
    generatedAt: $generatedAt,
    script: "scripts/mesh-mode/check-upstream-state.sh",
    commit: $commit,
    dirty: $dirty,
    exitStatus: $status,
    host: { kind: "operator workstation", os: $os, kernel: $kernel, arch: $arch },
    tools: ({ fetchedWith: $fetcher, curl: $curl, jq: $jq, python3: $python3 } + (if $gh == "" then {} else { gh: $gh } end)),
    upstream: { istioLatest: $istioTag, spireLatest: $spireTag }
  }' > "$ENVIRONMENT"

note "record written to ${RECORD#"$REPO"/} and ${ENVIRONMENT#"$REPO"/}"
for m in "${moved[@]}"; do note "MOVED: $m"; done
for u in "${unreachable[@]}"; do note "UNREACHABLE: $u"; done
for n in "${notes[@]}"; do note "NOTE: $n"; done
case $status in
  0) note "premises hold (exit 0)";;
  1) note "a premise moved (exit 1)";;
  2) note "a source was unreachable; no claim is made about it (exit 2)";;
esac
exit $status
