# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Admission control
  Annex A rows for Admission control, worded exactly as in the Annex.

  @ZT-02 @BDD-ZT-002 @pending
  Scenario: Secure Execution Environment
    Given the target Kubernetes environment is ready and the approved signed release artefacts are available
    When the Zero Trust execution environment is deployed
    Then only artefacts satisfying the configured admission and trust controls reach Running state AND an unsigned or non-compliant artefact is rejected before execution.

  @ZT-11 @BDD-ZT-011 @pending
  Scenario: OPA Gatekeeper
    Given OPA Gatekeeper deployed with the client trust anchor published via did:web over TSA and linked in TRAIN, and the signing key material held in OpenBao
    When pods are created from a correctly signed image and from an unsigned image
    Then the signed image is admitted and the unsigned image is blocked at pod creation AND additional governance Rego policies, such as allowed registries and naming conventions, are enforced through Gatekeeper.

  @ZT-12 @BDD-ZT-012 @pending
  Scenario: OPA Policy Repository
    Given an approved Rego policy package in the FACIS source repository
    When the GitHub Actions policy workflow runs
    Then the policy artefact is built and pushed to Harbor via OCI and Gatekeeper loads the published policy AND an unavailable or invalid policy package is not treated as an approved admission policy.

  @ZT-36 @BDD-ZT-036 @pending
  Scenario: OPA Gatekeeper
    Given OPA Gatekeeper deployed together with the XFSC TSA Policy Service and a published Rego policy package
    When a workload subject to that policy is submitted for admission
    Then Gatekeeper loads the policy through the TSA Policy Service and enforces the decision AND a workload violating the policy is denied at admission.

  @ZT-37 @BDD-ZT-037 @pending
  Scenario: OPA Gatekeeper Policies
    Given an approved Gatekeeper/Rego policy source in the FACIS repository
    When the policy publication workflow runs
    Then the policy package is built and published to Harbor and the required GitHub push action completes successfully.

  @ZT-72 @BDD-ZT-072 @cluster
  Scenario: Secure Pod Startup
    Given Gatekeeper is configured with the approved admission policy
    When one correctly signed image and one unsigned/non-compliant image are submitted for pod creation
    Then the signed compliant pod may start AND the unsigned/non-compliant pod is denied before startup.
