# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Attested channel
  Annex A rows for Attested channel, worded exactly as in the Annex.

  @ZT-04 @BDD-ZT-004 @pending
  Scenario: Secure Connection
    Given two configured Zero Trust Connectors with trusted identities
    When Connector A initiates a connection to Connector B
    Then an authenticated protected channel is established before application traffic is forwarded AND a peer that cannot establish the required trusted channel receives no application traffic.

  @ZT-19 @BDD-ZT-019 @pending
  Scenario: Upstream / Downstream Proxy Functionality
    Given two Zero Trust Connectors with an established attested TLS channel
    When an upstream request including relevant HTTP/gRPC metadata is forwarded through the connector pair
    Then the request reaches the counter side over that protected channel with required call information preserved AND no unprotected inter-connector path is used.

  @ZT-28 @BDD-ZT-028 @pending
  Scenario: Attested TLS
    Given two ZT Connectors in different clusters
    When they establish inter-cluster communication
    Then the channel uses mutually attested TLS with TLS 1.3 or later and certificates are checked against cluster identity AND a TLS version below 1.3 or failed identity/attestation validation prevents channel establishment.

  @ZT-29 @BDD-ZT-029 @pending
  Scenario: Attestation Request
    Given a Connector initiates an attested-TLS handshake
    When it creates an attestation request
    Then the request is machine-readable and states the requested server-side, client-side or mutual attestation mode AND malformed requests or unsupported required attestation information do not advance the handshake.

  @ZT-30 @BDD-ZT-030 @pending
  Scenario: Attestation Response
    Given a valid machine-readable attestation request
    When the peer creates its response
    Then the response contains the required attestation report (or an empty/null report where none was requested) and respects the specified size constraint AND malformed responses are rejected by the receiving protocol flow.

  @ZT-31 @BDD-ZT-031 @pending
  Scenario: Attestation Report Format
    Given an attestation report received during the TLS handshake
    When the peer verifies it
    Then the report signature is cryptographically verifiable, required supporting information is available, and the TLS-exporter channel binding matches the active TLS channel AND a report with invalid signature or channel binding is rejected.

  @ZT-32 @BDD-ZT-032 @pending
  Scenario: Verification Result Message
    Given a peer has completed attestation-report verification
    When it sends the verification-result message
    Then the message is machine-readable and affirmative only after successful verification AND a failed verification never produces an affirmative result.

  @ZT-33 @BDD-ZT-033 @pending
  Scenario: Error Message
    Given an error occurs at any defined step of the attestation protocol
    When the peer handles the error
    Then it emits a machine-readable error containing a useful human-readable diagnostic and closes the TLS connection AND no application-layer communication continues after the error.

  @ZT-34 @BDD-ZT-034 @pending
  Scenario: Proxy Integration
    Given an Ingress or Gateway API resource declaring an attested-TLS-protected route
    When the resource is applied and a peer connector initiates an attested connection
    Then the reverse proxy accepts the attested upstream connection and routes it to the configured in-mesh backend AND a route whose peer cannot be attested receives no application traffic.

  @ZT-63 @BDD-ZT-063 @pending
  Scenario: TEE Mock Setup
    Given the demonstrator remote-attestation environment
    When the TEE mock is started
    Then it produces the defined mock measurement/attestation material in the format required by the attested-TLS flow AND malformed/unavailable mock attestation material is not accepted as trusted evidence.

  @ZT-65 @BDD-ZT-065 @pending
  Scenario: Connection Start
    Given Connector 1 is configured to establish an attested connection to Connector 2
    When the connection starts
    Then Connector 1 sends the required machine-readable attestation request and the handshake enters the attestation flow.

  @ZT-66 @BDD-ZT-066 @pending
  Scenario: Remote Attestation
    Given Connector 2 receives a valid attestation request
    When it performs remote attestation
    Then it creates the required attestation report and sends it to Connector 1 in the protocol response.

  @ZT-67 @BDD-ZT-067 @pending
  Scenario: Attestation Report Verification
    Given Connector 1 has received Connector 2's attestation report and the expected mocked TEE measurement from the TCR/TRAIN path
    When verification is executed
    Then the observed and expected values plus cryptographic/channel-binding checks are validated AND any mismatch causes verification failure.

  @ZT-68 @BDD-ZT-068 @pending
  Scenario: Verification Result
    Given Connector 1 has completed verification of Connector 2's attestation report
    When it issues the verification-result message
    Then Connector 2 receives a machine-readable result reflecting the actual outcome AND a failed verification is reported as failure, never as success.

  @ZT-69 @BDD-ZT-069 @pending
  Scenario: Established Connection
    Given a successful attested-TLS handshake between two Connectors
    When application traffic is sent over the established channel
    Then the traffic is carried end to end over that channel AND traffic offered before the handshake completes is not carried.

  @ZT-70 @BDD-ZT-070 @pending
  Scenario: Refused Connection
    Given the peer attestation report or handshake is invalid
    When the inter-cluster connection is established
    Then the protocol terminates and no application-layer communication is possible.
