# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Credential lifecycle
  Annex A rows for Credential lifecycle, worded exactly as in the Annex.

  @ZT-40 @BDD-ZT-040 @pending
  Scenario: Credential-Based Access Control (CrBAC)
    Given a participant backend with a valid credential presentation and DPoP-capable client identity
    When it accesses the counter-side protected resource through the ZT Connector
    Then the Connector obtains/maintains the counter-side access token via OCM/OID4VP, validates DPoP, substitutes the correct upstream authorization and returns the protected response AND revoked/invalid credentials, invalid DPoP or unusable tokens result in denial.

  @ZT-51 @BDD-ZT-051 @pending
  Scenario: Credential Revocation
    Given a credential is revoked or revocation status cannot be verified
    When the credential is presented for protected access
    Then verification fails closed and the protected resource is not reached.
