# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Target environments
  Annex A rows for Target environments, worded exactly as in the Annex.

  @ZT-14 @BDD-ZT-014 @pending
  Scenario: T-Systems Open Sovereign Cloud Environment
    Given the T-Systems Open Sovereign Cloud environment provisioned for the demonstrator
    When the full Zero Trust stack is deployed to it
    Then the cluster and solution are reachable, all Zero Trust components reach Running state, OPA Gatekeeper demonstrably blocks an unsigned image, and an end-to-end connection between the ZT Connector and the protected resource is verified.

  @ZT-15 @BDD-ZT-015 @pending
  Scenario: IONOS Cloud Environment
    Given the IONOS Kubernetes environment and the approved visualization release
    When the visualization stack is deployed
    Then the FACIS Zero Trust Demonstrator visualization is reachable and operational on IONOS Cloud.

  @TDR-BDD-10 @BDD-TDR-010 @pending
  Scenario: External dependency reachability
    Given the target deployment
    When dependency health/connectivity checks are executed
    Then the required Keycloak and trust endpoints are reachable and their expected interfaces respond.
