# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Fail-secure behaviour
  Annex A rows for Fail-secure behaviour, worded exactly as in the Annex.

  @ZT-47 @BDD-ZT-047 @pending
  Scenario: Continuous Authentication Enforcement
    Given an authenticated session with a configurable re-validation interval of 15 minutes or less
    When protected-resource requests continue over time
    Then authentication and authorization are re-evaluated at the configured interval AND access is revoked automatically when the session becomes non-compliant.

  @ZT-52 @BDD-ZT-052 @pending
  Scenario: Fail-Secure (Fail-Closed) Behavior
    Given a required Zero Trust control-plane service becomes unavailable
    When protected access is requested
    Then access is denied, the failure is detected within 30 seconds and an alert/evidence record is produced.
