# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Management and data plane separation
  Annex A rows for Management and data plane separation, worded exactly as in the Annex.

  @ZT-49 @BDD-ZT-049 @pending
  Scenario: Micro-Segmentation
    Given workloads in separate policy-defined trust zones
    When authorized and unauthorized east-west connections are attempted
    Then permitted zone-to-zone traffic is inspected and authorized AND unauthorized lateral movement is blocked and logged.

  @ZT-53 @BDD-ZT-053 @pending
  Scenario: Multi-Tenancy and Tenant Isolation
    Given two organizational tenants represented by separate Kubernetes namespaces
    When each tenant accesses its own and the other tenant's data, credentials or policy configuration
    Then own-tenant access follows authorization policy AND cross-tenant access is denied and evidenced.

  @ZT-55 @BDD-ZT-055 @pending
  Scenario: Management Plane / Data Plane Separation
    Given management-plane services and application/data-plane workloads are deployed
    When reachability is tested from both planes
    Then management services are reachable only through dedicated control channels and are separated by network-policy and service-mesh controls AND data-plane compromise/reachability does not provide access to management-plane endpoints.
