# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Policy decision
  Annex A rows for Policy decision, worded exactly as in the Annex.

  @ZT-06 @BDD-ZT-006 @pending
  Scenario: Attribute/Credential Based Access Control
    Given one participant backend with the required credential attributes and one without them
    When both request the same protected resource
    Then the authorized request is permitted according to credential/policy evaluation AND the request without matching attributes/authorization is denied and evidenced.

  @ZT-41 @BDD-ZT-041 @pending
  Scenario: Protected Resource Mockup
    Given the protected-resource mock configured with role-differentiated responses
    When it is called with access tokens carrying different roles
    Then each role receives its configured response AND a token carrying no permitted role receives no protected content.

  @ZT-75 @BDD-ZT-075 @pending
  Scenario: Protected Resource Mock
    Given the protected-resource mock exposes responses for different access roles
    When requests with different authorized and unauthorized roles are executed
    Then role-appropriate responses are returned and visualized AND unauthorized roles do not receive protected content.
