# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Release quality
  Annex A rows for Release quality, worded exactly as in the Annex.

  @TDR-BDD-09 @BDD-TDR-009 @pending
  Scenario: Required Kubernetes objects
    Given a successful release deployment
    When the Kubernetes resources are inspected
    Then the required namespace, ingress, service and deployment objects exist and are ready.

  @TDR-BDD-11 @BDD-TDR-011 @pending
  Scenario: Helm lint and dry-run
    Given a release candidate
    When its Helm chart enters the CI quality gate
    Then helm lint and helm dry-run both pass before the release can be promoted.
