# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Security baseline
  Annex A rows for Security baseline, worded exactly as in the Annex.

  @ZT-50 @BDD-ZT-050 @pending
  Scenario: Cryptographic Standards (BSI TR-02102)
    Given the deployed demonstrator configuration and generated cryptographic artefacts
    When algorithms, key lengths, hashes and TLS settings are inspected
    Then only BSI TR-02102-compliant algorithms/strengths are present and auditable AND deprecated algorithms such as MD5, SHA-1 or insufficient RSA key lengths are absent/rejected.

  @TDR-BDD-07 @BDD-TDR-007 @pending
  Scenario: TLS 1.3 runtime validation
    Given the deployed endpoints
    When TLS 1.3 and an older TLS version are attempted
    Then TLS 1.3 succeeds where authorized and the older protocol version is rejected.

  @TDR-BDD-08 @BDD-TDR-008 @pending
  Scenario: Secrets and log masking
    Given the deployed release and CI/CD logs
    When secret storage and log output are inspected
    Then required credentials are held in Kubernetes Secrets and no plaintext secret value is present in logs.
