# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Supply chain
  Annex A rows for Supply chain, worded exactly as in the Annex.

  @ZT-10 @BDD-ZT-010 @pending
  Scenario: Image Signing and Attestation
    Given the approved GitHub runner, signing key material and a release image
    When the image-signing and mock-attestation workflow runs
    Then the image is signed and the attestation artefact is produced by the authorized pipeline AND a release without the required signature cannot pass the admission path.

  @ZT-13 @BDD-ZT-013 @pending
  Scenario: Linux-based Docker Images
    Given the release image set for the demonstrator
    When the images are inspected and deployed to the target cluster
    Then every image is Linux-based and reaches Running state AND an image that is not Linux-based is rejected before deployment.

  @ZT-38 @BDD-ZT-038 @pending
  Scenario: Container Signing Pipeline
    Given a release image and the client-controlled signing setup
    When the GitHub Actions signing workflow completes
    Then the image signature is published and Gatekeeper accepts the correctly signed image AND an unsigned or incorrectly signed image is rejected at admission.

  @ZT-54 @BDD-ZT-054 @pending
  Scenario: Software Bill of Materials (SBOM)
    Given a release build in the CI/CD pipeline
    When the release workflow completes
    Then an SBOM in CycloneDX or SPDX format is generated automatically, signed with the client key material and published in the repository alongside the release artefacts AND a release without a signed SBOM does not pass the release gate.

  @ZT-56 @BDD-ZT-056 @pending
  Scenario: CI/CD Pipeline Security (Zero Trust for the Pipeline)
    Given the project GitHub Actions workflows and branch-protection configuration
    When a pipeline run and a merge to main are attempted
    Then all third-party actions are pinned to commit SHAs, the run holds only the minimum required permissions, no secret value appears in any log, artefacts are signed before use and the run is logged AND a merge to main without the required review is refused.

  @ZT-71 @BDD-ZT-071 @pending
  Scenario: Image Signing and mock Attestation
    Given a defined set of Harbor images and the approved CI/CD signing setup
    When the secure-execution release workflow runs
    Then those images are signed, signatures are uploaded to Harbor and a JSON mock-attestation artefact is generated AND an image lacking the expected signature/attestation cannot satisfy the secure-execution gate.
