# Code generated by cmd/bddpack from features/annex/annex-a.json. DO NOT EDIT.
Feature: Expected measurements and trust lists
  Annex A rows for Expected measurements and trust lists, worded exactly as in the Annex.

  @ZT-03 @BDD-ZT-003 @pending
  Scenario: Trust Zone
    Given the two federation zones are deployed as separate participants in isolated cluster contexts
    When the configured trust relationship between them is exercised
    Then each zone resolves the other as an explicitly configured participant AND a zone outside the configured relationship is not resolvable as a participant.

  @ZT-18 @BDD-ZT-018 @pending
  Scenario: TRAIN Allow List
    Given a TRAIN trust list naming the permitted counter-connector
    When connections are attempted from a listed and from an unlisted counter-connector
    Then the listed peer is admitted on the basis of the retrieved trust list AND the unlisted peer is refused.

  @ZT-35 @BDD-ZT-035 @pending
  Scenario: Hash Management/TRAIN Integration
    Given each attested-TLS endpoint has published its expected launch digest/measurement to TRAIN
    When a peer connection is established
    Then the remote expected hash is resolved from TRAIN and compared with the received attestation report AND a missing or mismatching trusted hash prevents connection establishment.

  @ZT-64 @BDD-ZT-064 @pending
  Scenario: Expected Measurement Retrieval
    Given a counter-connector has published its expected mocked TEE measurement to TRAIN
    When the Connector prepares to verify that peer
    Then it retrieves the expected measurement from TRAIN and uses it for comparison AND a peer with no published measurement cannot be verified.
