#!/usr/bin/env bash
# Regenerates the wrapper-isolation evidence: the import guard, the wrapper test run and the freeze of
# the wrapper's exported API at v1.
#
#   depguard-run.txt   golangci-lint on the clean tree, then with throwaway imports of CMC and of
#                      the test-only atlstest package planted outside internal/atls (each must
#                      fail and name the import), then clean again after removing them.
#   atls-test-run.txt  go test of internal/atls, plain and under the race detector.
#   api-freeze.txt     the commit at which the exported API was frozen, the listing as frozen
#                      (internal/atls/api_v1.txt), and the API guard: passing on the clean tree,
#                      failing and naming throwaway exported identifiers planted in the package,
#                      passing again after removing them.
#
# It ends with one line per proof and exits non-zero unless all three hold.
#
# Usage: prove-isolation.sh            (golangci-lint on PATH, or GOLANGCI_LINT=/path/to/it)
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
root=$(git -C "$here" rev-parse --show-toplevel)
lint=${GOLANGCI_LINT:-golangci-lint}
cd "$root"

probe_dir=internal/bddreport
cmc_probe=$probe_dir/zz_cmc_guard_probe.go
atlstest_probe=$probe_dir/zz_atlstest_guard_probe.go
cmc_test_probe=$probe_dir/zz_cmc_guard_probe_test.go
api_listing=internal/atls/api_v1.txt
api_probe=internal/atls/zz_api_freeze_probe.go
contract=docs/attested-channel.md
cleanup() { rm -f "$cmc_probe" "$atlstest_probe" "$cmc_test_probe" "$api_probe"; }
trap cleanup EXIT

tree() {
	echo "tree: $(git rev-parse HEAD)$(git diff --quiet HEAD -- . ':!docs/evidences' || echo ' + uncommitted changes')"
}

# run_lint ARG...: runs golangci-lint, prints its exit status and leaves it in $status.
run_lint() {
	status=0
	"$lint" run "$@" || status=$?
	echo "exit status: $status"
}

# run_guard: runs the API guard test, prints its output and exit status, leaves them in
# $guard_output and $status.
run_guard() {
	status=0
	guard_output=$(go test -count=1 -run '^TestExportedAPIFrozen$' -v ./internal/atls 2>&1) || status=$?
	echo "$guard_output"
	echo "exit status: $status"
}

imports_ok=yes
{
	echo "# Import guard (depguard) — generated by prove-isolation.sh"
	echo
	echo "$("$lint" --version)"
	echo "$(go version)"
	tree
	echo

	echo "## 1. Clean tree: no package outside internal/atls imports CMC"
	echo '$ golangci-lint run ./...'
	run_lint ./...
	[ "$status" -eq 0 ] || imports_ok=no
	echo

	echo "## 2. Throwaway import of CMC from a non-test file of $probe_dir"
	cat >"$cmc_probe" <<'EOF'
package bddreport

import _ "github.com/Fraunhofer-AISEC/cmc/attestedtls"
EOF
	echo "\$ cat $cmc_probe"
	cat "$cmc_probe"
	echo "\$ golangci-lint run ./$probe_dir/..."
	run_lint "./$probe_dir/..."
	[ "$status" -ne 0 ] || imports_ok=no
	rm -f "$cmc_probe"
	echo

	echo "## 3. Throwaway import of CMC from a test file of $probe_dir"
	cat >"$cmc_test_probe" <<'EOF'
package bddreport

import _ "github.com/Fraunhofer-AISEC/cmc/attestationreport"
EOF
	echo "\$ cat $cmc_test_probe"
	cat "$cmc_test_probe"
	echo "\$ golangci-lint run ./$probe_dir/..."
	run_lint "./$probe_dir/..."
	[ "$status" -ne 0 ] || imports_ok=no
	rm -f "$cmc_test_probe"
	echo

	echo "## 4. Throwaway import of the test-only atlstest package from a non-test file"
	cat >"$atlstest_probe" <<'EOF'
package bddreport

import _ "github.com/eclipse-xfsc/facis-zero-trust-demonstrator/internal/atls/atlstest"
EOF
	echo "\$ cat $atlstest_probe"
	cat "$atlstest_probe"
	echo "\$ golangci-lint run ./$probe_dir/..."
	run_lint "./$probe_dir/..."
	[ "$status" -ne 0 ] || imports_ok=no
	rm -f "$atlstest_probe"
	echo

	echo "## 5. Throwaway imports removed: clean again"
	echo '$ golangci-lint run ./...'
	run_lint ./...
	[ "$status" -eq 0 ] || imports_ok=no
} >"$here/depguard-run.txt" 2>&1

tests_ok=yes
{
	echo "# internal/atls tests — generated by prove-isolation.sh"
	echo
	echo "$(go version)"
	tree
	echo
	echo '$ go test -count=1 -v ./internal/atls/...'
	status=0
	go test -count=1 -v ./internal/atls/... 2>&1 | grep -E '^(=== RUN|--- |PASS|FAIL|ok|    )' || status=$?
	echo
	echo '$ go test -race -count=1 ./internal/atls/...'
	go test -race -count=1 ./internal/atls/... 2>&1 || status=$?
	[ "$status" -eq 0 ] || tests_ok=no
} >"$here/atls-test-run.txt"

# The interface was frozen at the last commit that changed the listing.
frozen=$(git log -1 --format=%H -- "$api_listing")
frozen_date=$(git log -1 --format=%cs -- "$api_listing")
api_ok=yes
[ -n "$frozen" ] || api_ok=no
{
	echo "# API freeze (v1) — generated by prove-isolation.sh"
	echo
	echo "$(go version)"
	tree
	echo
	echo "frozen commit: ${frozen:-none} (${frozen_date:-no date})"
	echo "The frozen commit is the last commit that changed $api_listing, the listing of the"
	echo "exported API of internal/atls."
	if git diff --quiet HEAD -- "$api_listing"; then
		echo "The listing in this tree is the one of that commit."
	else
		echo "The listing in this tree has uncommitted changes: it is NOT the one of that commit."
		api_ok=no
	fi
	if [ -n "$frozen" ] && grep -q "frozen at \`${frozen:0:7}\`" "$contract"; then
		echo "$contract names the frozen commit: yes (\`${frozen:0:7}\`)"
	else
		echo "$contract names the frozen commit: NO"
		api_ok=no
	fi
	echo

	echo "## 1. The listing as frozen"
	echo "\$ cat $api_listing"
	cat "$api_listing"
	echo

	echo "## 2. Clean tree: the package matches the listing"
	echo "\$ go test -count=1 -run '^TestExportedAPIFrozen\$' -v ./internal/atls"
	run_guard
	[ "$status" -eq 0 ] || api_ok=no
	echo

	echo "## 3. Throwaway exported identifiers planted in internal/atls"
	cat >"$api_probe" <<'EOF'
package atls

// Throwaway is a throwaway exported method that proves the API guard.
func (c *Conn) Throwaway() int { return 0 }

// ErrThrowaway is a throwaway exported sentinel that proves the API guard.
var ErrThrowaway error
EOF
	echo "\$ cat $api_probe"
	cat "$api_probe"
	echo "\$ go test -count=1 -run '^TestExportedAPIFrozen\$' -v ./internal/atls"
	run_guard
	[ "$status" -ne 0 ] || api_ok=no
	# The guard names each identifier that differs.
	case $guard_output in *'method (*Conn) Throwaway() int'*) ;; *) api_ok=no ;; esac
	case $guard_output in *'var ErrThrowaway error'*) ;; *) api_ok=no ;; esac
	rm -f "$api_probe"
	echo

	echo "## 4. Throwaway identifiers removed: the package matches the listing again"
	echo "\$ go test -count=1 -run '^TestExportedAPIFrozen\$' -v ./internal/atls"
	run_guard
	[ "$status" -eq 0 ] || api_ok=no
	echo

	echo "## Outcome of this run"
	echo "import guard:  $([ "$imports_ok" = yes ] && echo pass || echo FAIL) (depguard-run.txt)"
	echo "wrapper tests: $([ "$tests_ok" = yes ] && echo pass || echo FAIL) (atls-test-run.txt)"
	echo "API guard:     $([ "$api_ok" = yes ] && echo pass || echo FAIL)"
	echo "frozen commit: ${frozen:-none}"
} >"$here/api-freeze.txt" 2>&1

echo "wrote $here/depguard-run.txt, $here/atls-test-run.txt and $here/api-freeze.txt"
sed -n '/^## Outcome of this run$/,$p' "$here/api-freeze.txt" | tail -n +2
[ "$imports_ok" = yes ] && [ "$tests_ok" = yes ] && [ "$api_ok" = yes ]
