{{- range $identity := list .Values.deployer .Values.observer }}
{{- if $identity.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $identity.serviceAccount.name }}
  namespace: {{ include "pool.saNamespace" (dict "root" $ "sa" $identity.serviceAccount) }}
  labels:
    {{- include "pool.labels" $ | nindent 4 }}
{{- end }}
{{- end }}
